### PR TITLE
Fixed Wordbreak on confirmation mobile screens

### LINKED ISSUE #319: Email looks like sucks
The Vancouver IRCC email address is super long: IRCC.DNCitVANNotification-NotificationVANCitRN.IRCC@cic.gc.ca

We put in some [CSS word-break stuff](https://css-tricks.com/snippets/css/prevent-long-urls-from-breaking-out-of-container/) so that the email will fit on the screen. So now the email breaks across lines, but we don't really decide how that's happening.

| before | after |
|--------|-------|
| image from ios  |  image from ios 1  |

Didn't really make it better.

**Proposed solution:**

Let's:
- take out the word-break CSS
- make the link a block-level element
- use [`<wbr>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/wbr) elements so that the email breaks where we want it (on mobile).

Like this:
```html
<a href="mailto:IRCC.DNCitVANNotification-NotificationVANCitRN.IRCC@cic.gc.ca">
  IRCC.DNCitVANNotification-<wbr />NotificationVANCitRN.IRCC<wbr />@cic.gc.ca
</a>
```

Should look like this:
screen shot 2018-08-01 at 10 10 59 pm

👍

### PR DESCRIPTION
**Pull request by nmakuch**
# This PR consists of:

## Fixing the horrendous wordbreak on the confirmation page:

| Before | After |
|--------|-------|
|   screen shot 2018-08-02 at 14 01 08     |   screen shot 2018-08-02 at 14 01 56    |

(Merging this PR closes #319 )

### CODE REVIEW

File: web/src/components/Contact.js [hunk 1]
```diff
@@ -24,7 +24,7 @@ const telStyles = css`
 const TelLink = ({ tel }) => (
   <span className={telStyles}>
     <span>{tel}</span>
-    <a href={`tel:+${tel}`} rel="nofollow">
+    <a name="telephone" href={`tel:+${tel}`} rel="nofollow">
```
Comment (pcraig3) [inline web/src/components/Contact.js]: uh oh, looks like `name` is deprecated in HTML5.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#Obsolete_attributes

Alternatively, you could just use `id="telephone"` or `class="telephone"`

File: web/src/components/Contact.js [hunk 2]
```diff
@@ -35,23 +35,22 @@ TelLink.propTypes = {
...
+  wbr {
+    display: none;
+  }
+
+  ${mediaQuery.sm(css`
+    a[name='email'],
+    a[name='telephone'] {
+      display: block;
+    }
+    wbr {
```
Comment (pcraig3) [inline web/src/components/Contact.js]: Can we do the `wbr` rule only on `xs`?

File: web/src/components/Contact.js [hunk 3]
```diff
@@ -35,23 +35,22 @@ TelLink.propTypes = {
...
   p:first-of-type {
     margin-bottom: ${theme.spacing.sm};
   }
+  wbr {
+    display: none;
+  }
+
+  ${mediaQuery.xs(css`
+    a[id='email'],
+    a[id='telephone'] {
```
Comment (pcraig3) [inline web/src/components/Contact.js]: now that you're using ids, you can be like `a#telephone`, but it's fine either way, so just merging as-is is fine with me.
